spring:
  datasource:
    url: jdbc:mysql://db-mysql-cart-microservice-do-user-15773796-0.c.db.ondigitalocean.com:25060/defaultdb?sslMode=REQUIRED
    username: doadmin
    password: AVNS_SzbJkllAsg6YUP5VnK7
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081